### ISSUE TITLE
Docker / Multiple Issues

### ISSUE THREAD

**Issue by F1DNA** [TheHumanRobot/Rollarr#9]
1. Running in Docker on a separate system from my Plex server

Docker compose (Portainer):

```
services:
  rollarr:
    image: thehumanrobot/rollarr:latest
    container_name: rollarr
    volumes:
      - /home/user/docker/data/rollarr/data.json:/docker/configs/rollarr/data.json
      - /mnt/media:/mnt/media
    ports:
      - 3100:3100
    environment:
      - TZ=America/Chicago
    restart: unless-stopped
```

Host:
```
xxx@xxx:/$ ls /home/user/docker/data/rollarr/data.json/
xxx@xxx:/$
```
Container:
```
root@32feb434fd25:/# ls /docker/configs/rollarr/data.json/
root@32feb434fd25:/# 
```
Figuring you likely need to set some prerolls to generate the config file, I went ahead and set the "Default Files" and hit both "Save" And "Submit" to no avail

2. The "Test Connection" button does not appear to do anything

3. My plex prerolls field does not update either

I have ensured I mounted my NAS share to my Docker host exactly how it is mounted on my Plex Server (both are Ubuntu Server)
